// Unit tests for the @stable auto-removal's staging set and its commit check (#1822).
// Run with: npm run test:scripts
//
// Two halves, and the second one is the one that fails against the defect.
//
// The pure half asserts what `removed[].file` turns into. The behavioural half
// EXTRACTS the commit step from `.github/actions/auto-remove-stable/action.yml` and
// runs it under `bash` against a real git repository with a real remote, because the
// defect this closes lived entirely in that shell block: `git add` with one fixed path
// prefix, over a script that edits whatever spec the report names. Asserting on the
// YAML's text would have passed against it (#1226's lesson — a guard that pins a
// spelling does not pin a behaviour), and so did the unit tests that existed.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { execFileSync, spawnSync } from "node:child_process";

import {
  UnusableReportError,
  main,
  missingFromCommit,
  splitNulList,
  stagingPaths,
} from "./auto-remove-commit-paths.mjs";
import { makeTempDir } from "./lib/tmp-dir.mjs";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const SCRIPT = path.join(REPO_ROOT, "scripts", "auto-remove-commit-paths.mjs");
const ACTION = path.join(
  REPO_ROOT,
  ".github",
  "actions",
  "auto-remove-stable",
  "action.yml",
);

const REGRESSION_SPEC =
  "tests/tests-automations/regression/core-functionality/model-provider/anthropic-provider.spec.ts";
const OUTSIDE_SPEC = "tests/collect-models.spec.ts";
// The four behavioural gates are the 27 tests still in that blind spot today;
// `tests/collect-models.spec.ts` was the 28th until #1822 took its tag off for
// reasons of its own, and is kept here because it is the file the run lost.
const GATE_SPEC = "tests/fixtures/flow-error-gate.spec.ts";

const removal = (file, title = "a hard-failing test") => ({
  file,
  title,
  line: 39,
  soleTag: false,
});

/** The shape `remove-stable-from-failures.ts` writes, trimmed to what this reads. */
const report = (files) => ({
  status: "removed",
  threshold: 5,
  hardFailures: files.length,
  attributableFailures: files.length,
  removed: files.map((f) => removal(f)),
  skipped: [],
  exempt: [],
  disagreements: [],
});

// ---------- the staging set ----------

test("a removal outside tests/tests-automations/regression/ is staged like any other", () => {
  // The defect, stated as an assertion: the prefix reached the first of these and
  // not the second, and the step was green either way.
  assert.deepEqual(stagingPaths(report([REGRESSION_SPEC, OUTSIDE_SPEC])), [
    OUTSIDE_SPEC,
    REGRESSION_SPEC,
  ]);
  assert.deepEqual(stagingPaths(report([GATE_SPEC])), [GATE_SPEC]);
});

test("two removals in one file stage that file once", () => {
  const two = {
    ...report([]),
    removed: [removal(OUTSIDE_SPEC, "first"), removal(OUTSIDE_SPEC, "second")],
  };
  assert.deepEqual(stagingPaths(two), [OUTSIDE_SPEC]);
});

test("QA-CHECKLIST.md is not in the derived set — it is the step's own explicit add", () => {
  // It is regenerated by the step rather than reported by the script, and it may
  // legitimately produce no diff. This function answers one question only: which
  // paths did the script say it edited.
  assert.ok(!stagingPaths(report([REGRESSION_SPEC])).includes("QA-CHECKLIST.md"));
});

test("an empty removal set derives an empty staging set rather than everything", () => {
  assert.deepEqual(stagingPaths(report([])), []);
});

test("a report this cannot read is refused, never silently staged as nothing", () => {
  // Staging nothing IS the defect — it must not be reachable by degrading.
  for (const bad of [null, [], "removed", { status: "removed" }, { removed: {} }]) {
    assert.throws(() => stagingPaths(bad), UnusableReportError, `accepted ${JSON.stringify(bad)}`);
  }
  for (const bad of [null, 42, "", "   ", undefined]) {
    assert.throws(
      () => stagingPaths({ removed: [{ file: bad }] }),
      UnusableReportError,
      `accepted file=${JSON.stringify(bad)}`,
    );
  }
});

test("a path that would not mean itself as a git pathspec is refused", () => {
  for (const bad of [
    "/etc/passwd",
    "tests/../../elsewhere/x.spec.ts",
    "../x.spec.ts",
    ":(glob)tests/**",
    ":/x.spec.ts",
  ]) {
    assert.throws(
      () => stagingPaths({ removed: [{ file: bad }] }),
      UnusableReportError,
      `accepted ${bad}`,
    );
  }
});

// ---------- the commit check ----------

test("a reported removal absent from the commit is named", () => {
  const missing = missingFromCommit(report([REGRESSION_SPEC, OUTSIDE_SPEC]), [
    REGRESSION_SPEC,
    "QA-CHECKLIST.md",
  ]);
  assert.deepEqual(missing, [OUTSIDE_SPEC]);
});

test("a commit carrying every reported removal has nothing missing", () => {
  assert.deepEqual(
    missingFromCommit(report([REGRESSION_SPEC, OUTSIDE_SPEC]), [
      "QA-CHECKLIST.md",
      OUTSIDE_SPEC,
      REGRESSION_SPEC,
    ]),
    [],
  );
});

test("an empty commit listing leaves every reported removal missing", () => {
  assert.deepEqual(missingFromCommit(report([OUTSIDE_SPEC]), []), [OUTSIDE_SPEC]);
});

test("the -z stream is split on NUL and on nothing else", () => {
  assert.deepEqual(splitNulList("a\0b\0"), ["a", "b"]);
  assert.deepEqual(splitNulList(""), []);
  // A newline and a leading space are legal in a path, so splitting or trimming
  // on them corrupts the names `-z` exists to carry — and then reports the result
  // as a removal the commit does not contain.
  assert.deepEqual(splitNulList("a\nb\0"), ["a\nb"]);
  assert.deepEqual(splitNulList(" a \0"), [" a "]);
  // A caller that forgets `-z` gets one entry, not a plausible-looking list: every
  // reported path then reads as missing and the step fails, which is the safe way
  // round.
  assert.deepEqual(splitNulList("a\nb\n"), ["a\nb\n"]);
});

// ---------- the CLI ----------

function runCli(args, { stdin = "", files = {} } = {}) {
  const dir = makeTempDir("auto-remove-commit-paths-");
  for (const [name, content] of Object.entries(files)) {
    fs.writeFileSync(path.join(dir, name), content);
  }
  const resolved = args.map((a) => (files[a] ? path.join(dir, a) : a));
  const run = spawnSync(process.execPath, [SCRIPT, ...resolved], {
    encoding: "utf8",
    input: stdin,
    env: { PATH: process.env.PATH },
  });
  return { status: run.status, stdout: run.stdout, stderr: run.stderr };
}

test("`paths` emits NUL-separated, `:(literal)`-prefixed pathspecs", () => {
  const run = runCli(["paths", "r.json"], {
    files: { "r.json": JSON.stringify(report([OUTSIDE_SPEC, REGRESSION_SPEC])) },
  });
  assert.equal(run.status, 0);
  // The prefix is what makes each entry mean its own file: `--pathspec-file-nul`
  // disables unquoting, not wildmatch, so a bare `tests/*` would stage every
  // modified file under `tests/` (measured, git 2.52).
  assert.equal(
    run.stdout,
    `:(literal)${OUTSIDE_SPEC}\0:(literal)${REGRESSION_SPEC}\0`,
  );
});

test("a wildcard in the report aborts the staging instead of widening it", () => {
  // Unreachable from the producer (`removed[].file` is a path that passed
  // `fs.existsSync`), and pinned anyway: this is the `git add -A` the step exists
  // to avoid, arriving through the report instead of through the YAML.
  const ws = workspace({ removed: ["tests/*"], edits: [OUTSIDE_SPEC] });
  const run = runCommitStep(ws);
  assert.notEqual(run.status, 0, run.out);
  assert.match(run.out, /did not match any files/);
  assert.equal(git(ws.remote, "rev-parse", "main"), ws.baseline);
});

test("`verify` exits 1 naming the removal the commit does not carry", () => {
  const run = runCli(["verify", "r.json"], {
    files: { "r.json": JSON.stringify(report([OUTSIDE_SPEC, REGRESSION_SPEC])) },
    stdin: `${REGRESSION_SPEC}\0QA-CHECKLIST.md\0`,
  });
  assert.equal(run.status, 1);
  assert.match(run.stderr, /^::error::/m);
  assert.match(run.stderr, new RegExp(OUTSIDE_SPEC.replace(/[/.]/g, "\\$&")));
  assert.ok(
    !run.stderr.includes(REGRESSION_SPEC),
    "the file that DID land must not be named as missing",
  );
});

test("`verify` exits 0 when the commit carries every reported removal", () => {
  const run = runCli(["verify", "r.json"], {
    files: { "r.json": JSON.stringify(report([OUTSIDE_SPEC])) },
    stdin: `${OUTSIDE_SPEC}\0QA-CHECKLIST.md\0`,
  });
  assert.equal(run.status, 0, run.stderr);
});

test("an unreadable or unknown invocation exits 2 rather than 0", () => {
  assert.equal(runCli(["paths", "/nope/missing.json"]).status, 2);
  assert.equal(
    runCli(["paths", "r.json"], { files: { "r.json": "{not json" } }).status,
    2,
  );
  assert.equal(runCli(["list", "r.json"], { files: { "r.json": "{}" } }).status, 2);
  assert.equal(main([process.execPath, SCRIPT]), 2);
});

// ---------- the step itself, executed ----------
//
// Extracted from the action and run under bash, for the reason the file header
// gives. Deliberately brittle in the safe direction: a renamed or reshaped step
// throws here instead of quietly asserting on nothing.

function commitStepBody() {
  const action = fs.readFileSync(ACTION, "utf8");
  const marker = "- name: Commit @stable removals to main";
  const start = action.indexOf(marker);
  assert.ok(start > 0, "the commit step must exist under its known name");
  const next = action.indexOf("\n    - name:", start + 10);
  const step = next === -1 ? action.slice(start) : action.slice(start, next);
  const runAt = step.indexOf("run: |");
  assert.ok(runAt > 0, "the commit step must still be an inline shell block");
  const body = step
    .slice(step.indexOf("\n", runAt) + 1)
    .split("\n")
    .map((line) => line.replace(/^ {8}/, ""))
    .join("\n");
  assert.match(body, /^git commit -m "\$MSG"$/m, "the step must still commit");
  assert.match(body, /^git push$/m, "the step must still push");
  return body;
}

/**
 * git, insulated from whoever is running the test.
 *
 * The fixture builds a real repository and commits in it, so the developer's own
 * `~/.gitconfig` would otherwise decide whether that works: with
 * `commit.gpgsign = true` — an ordinary setting — every behavioural test below
 * dies in setup with `gpg failed to sign the data`, and CI, being a clean
 * container, never shows it. Same class as the repo's other environment-dependent
 * assertions (timezone, base URL, clone depth).
 *
 * The step UNDER test gets its own explicit env in `runCommitStep`, including
 * `HOME`, so nothing here ever writes to the developer's global config either.
 */
const git = (cwd, ...args) =>
  execFileSync("git", args, {
    cwd,
    encoding: "utf8",
    env: {
      ...process.env,
      GIT_CONFIG_GLOBAL: "/dev/null",
      GIT_CONFIG_SYSTEM: "/dev/null",
    },
  }).trim();

/**
 * A repository shaped like the workspace this step runs in: a checkout with a
 * remote, the two spec files the report can name, a checklist, and the script the
 * step calls.
 *
 * `edits` is what the auto-removal is pretending to have made — the workspace
 * modifications that are already there when this step starts.
 */
function workspace({ removed, edits, checklistChanges = true }) {
  const root = makeTempDir("auto-remove-step-");
  const repo = path.join(root, "repo");
  const remote = path.join(root, "remote.git");
  const home = path.join(root, "home");
  const bin = path.join(root, "bin");
  for (const dir of [repo, home, bin]) fs.mkdirSync(dir, { recursive: true });
  git(root, "init", "--bare", "-b", "main", remote);

  const write = (rel, content) => {
    const full = path.join(repo, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  };
  write("QA-CHECKLIST.md", "# checklist\n");
  write(REGRESSION_SPEC, 'test("a", { tag: ["@stable"] }, async () => {});\n');
  write(OUTSIDE_SPEC, 'test("b", { tag: ["@stable"] }, async () => {});\n');
  write(GATE_SPEC, 'test("c", { tag: ["@stable"] }, async () => {});\n');
  write(
    "scripts/auto-remove-commit-paths.mjs",
    fs.readFileSync(SCRIPT, "utf8"),
  );

  git(repo, "init", "-b", "main");
  git(repo, "config", "user.name", "fixture");
  git(repo, "config", "user.email", "fixture@example.com");
  git(repo, "add", "-A");
  git(repo, "commit", "-m", "baseline");
  git(repo, "remote", "add", "origin", remote);
  git(repo, "push", "-u", "origin", "main");
  const baseline = git(repo, "rev-parse", "HEAD");

  // The state the previous step leaves behind: the edited specs, plus the JSON
  // that says which ones they are.
  for (const rel of edits) {
    fs.writeFileSync(
      path.join(repo, rel),
      fs.readFileSync(path.join(repo, rel), "utf8").replace('"@stable"', ""),
    );
  }
  fs.writeFileSync(
    path.join(repo, "auto-remove-result.json"),
    JSON.stringify(report(removed)),
  );
  // Untracked run artifacts at the repo root — the reason `git add -A` is not the
  // fix. Their absence from the commit is asserted below.
  fs.writeFileSync(path.join(repo, "results.json"), "{}");
  fs.writeFileSync(path.join(repo, "payload.json"), "{}");

  // `npm run coverage:summary` stands in for the regeneration: the real one
  // rewrites QA-CHECKLIST.md from the edited specs.
  fs.writeFileSync(
    path.join(bin, "npm"),
    checklistChanges
      ? `#!/bin/sh\nprintf 'regenerated\\n' >> QA-CHECKLIST.md\n`
      : "#!/bin/sh\nexit 0\n",
    { mode: 0o755 },
  );

  return { root, repo, remote, home, bin, baseline };
}

function runCommitStep(ws) {
  const run = spawnSync("bash", ["-c", commitStepBody()], {
    cwd: ws.repo,
    encoding: "utf8",
    // Only what the step declares, plus what any shell needs. Anything it reads
    // and the action does not export would otherwise come from the developer's
    // environment.
    env: {
      PATH: `${ws.bin}:${process.env.PATH}`,
      HOME: ws.home,
      // `HOME` insulates the step from the developer's GLOBAL config — which it
      // writes to, via `git config --global --add safe.directory` — but not from
      // the SYSTEM one (`/etc/gitconfig`, `/opt/homebrew/etc/gitconfig`), where a
      // `commit.gpgsign = true` takes these tests down in exactly the same way.
      // Not pinned to a writable file, because the step must keep being able to
      // write its global config as it does on a runner.
      GIT_CONFIG_SYSTEM: "/dev/null",
      GITHUB_WORKSPACE: ws.repo,
      REMOVED_COUNT: "2",
      EXEMPT_COUNT: "0",
      RUN_LABEL: "daily #1",
    },
  });
  return { status: run.status, out: `${run.stdout}${run.stderr}` };
}

const committedFiles = (repo) =>
  git(repo, "diff-tree", "-r", "--no-commit-id", "--name-only", "HEAD")
    .split("\n")
    .filter(Boolean)
    .sort();

test("every reported removal reaches the commit, including one outside the old prefix", () => {
  // The regression test for #1822. Against the `git add tests/tests-automations/
  // regression QA-CHECKLIST.md` this replaces, the commit carries one of the two
  // and the step is green — exactly what run 34599745145 produced.
  const ws = workspace({
    removed: [REGRESSION_SPEC, OUTSIDE_SPEC],
    edits: [REGRESSION_SPEC, OUTSIDE_SPEC],
  });
  const run = runCommitStep(ws);
  assert.equal(run.status, 0, run.out);
  assert.deepEqual(committedFiles(ws.repo), [
    "QA-CHECKLIST.md",
    OUTSIDE_SPEC,
    REGRESSION_SPEC,
  ].sort());
  // Pushed, so the tag is gone on main and not only in the workspace.
  assert.equal(
    git(ws.remote, "rev-parse", "main"),
    git(ws.repo, "rev-parse", "HEAD"),
  );
  assert.notEqual(git(ws.repo, "rev-parse", "HEAD"), ws.baseline);
});

test("the untracked run artifacts at the repo root stay out of the commit", () => {
  const ws = workspace({ removed: [OUTSIDE_SPEC], edits: [OUTSIDE_SPEC] });
  assert.equal(runCommitStep(ws).status, 0);
  const files = committedFiles(ws.repo);
  for (const artifact of ["results.json", "payload.json", "auto-remove-result.json"]) {
    assert.ok(!files.includes(artifact), `${artifact} was committed`);
  }
});

test("a reported removal that did not reach the commit fails the step, unpushed", () => {
  // The second direction (#1084). The report names two files and only one was
  // edited, which is what a dropped edit looks like from here.
  const ws = workspace({
    removed: [REGRESSION_SPEC, OUTSIDE_SPEC],
    edits: [REGRESSION_SPEC],
  });
  const run = runCommitStep(ws);
  assert.notEqual(run.status, 0, "a removal that did not land must fail the step");
  assert.match(run.out, /::error::/);
  assert.ok(run.out.includes(OUTSIDE_SPEC), `the missing path must be named:\n${run.out}`);
  // Nothing reached main: the commit exists locally and the push never ran.
  assert.equal(git(ws.remote, "rev-parse", "main"), ws.baseline);
});

test("a removal set whose every edit was lost fails naming the cause, not git's", () => {
  const ws = workspace({
    removed: [OUTSIDE_SPEC],
    edits: [],
    checklistChanges: false,
  });
  const run = runCommitStep(ws);
  assert.notEqual(run.status, 0);
  assert.match(run.out, /::error::.*staged nothing/);
  assert.equal(git(ws.remote, "rev-parse", "main"), ws.baseline);
});

test("no lane stages the auto-removal by path prefix any more", () => {
  // The prefix reached four lanes' worth of nothing: it lived in one action, and
  // this is how it would come back — a second copy in a caller.
  const action = fs.readFileSync(ACTION, "utf8");
  // Over the COMMANDS only: the comment above the staging lines quotes the prefix
  // it replaced, and a guard that cannot tell prose from a command would forbid
  // recording why (#1822).
  const commands = action
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => !line.startsWith("#"));
  assert.ok(
    !commands.some((line) => /^git add .*tests\/tests-automations/.test(line)),
    "the commit step stages a path prefix again (#1822)",
  );
  assert.match(action, /auto-remove-commit-paths\.mjs paths/);
  assert.match(action, /auto-remove-commit-paths\.mjs verify/);
});

test("the CLI sets process.exitCode rather than calling process.exit", () => {
  // `paths` writes to a PIPE (`| git add`), and `process.exit()` discards whatever
  // has not flushed — the repo has measured that truncation at 8192 bytes. The
  // staging set is far under it, so nothing catches this by behaviour; it is
  // pinned here because the safe spelling is otherwise one edit from being lost.
  // Over the CODE only: the comment beside it names the spelling it rejects, and a
  // guard that cannot tell prose from a statement would forbid recording why.
  const code = fs
    .readFileSync(SCRIPT, "utf8")
    .split("\n")
    .filter((line) => !/^\s*(\/\/|\*|\/\*)/.test(line));
  assert.ok(
    !code.some((line) => /process\.exit\(/.test(line)),
    "the CLI calls process.exit()",
  );
  assert.ok(code.some((line) => /process\.exitCode = main\(/.test(line)));
});
